/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate user with email and password.
         *
         *     Args:
         *         email: User's email
         *         password: User's plain text password
         *
         *     Returns:
         *         User data (without password) if authentication successful
         *
         *     Raises:
         *         HTTPException: 401 if credentials are invalid
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Logout endpoint (placeholder).
         *
         *     Since JWTs are stateless, logout is handled on the client side by deleting the token.
         *
         *     Returns:
         *         Success message
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/service-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate Service Token
         * @description Generate a long-lived JWT token for service-to-service communication.
         *
         *     This endpoint is designed for creating tokens with extended expiration times
         *     for automated services (e.g., ML models, batch processors).
         *
         *     Args:
         *         user_credentials: Service account credentials (email/password)
         *         expiration_days: Token expiration in days (default: 365)
         *
         *     Returns:
         *         Long-lived JWT token
         *
         *     Raises:
         *         HTTPException: 401 if credentials are invalid
         *
         *     Example:
         *         curl -X POST "http://localhost:8000/auth/service-token?expiration_days=180" \
         *              -F "username=model-service@internal.com" \
         *              -F "password=123123"
         */
        post: operations["generate_service_token_auth_service_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/account-exists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Account User Exist
         * @description Check if any user account exists in the database.
         *
         *     Args:
         *         user_service: User service instance (injected dependency)
         *     Returns:
         *         Boolean indicating if any user account exists
         */
        get: operations["account_user_exist_auth_account_exists_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Info
         * @description Get current authenticated user's information.
         *
         *     Args:
         *         current_user: Current authenticated user (injected dependency)
         *         user_service: User service instance (injected dependency)
         *
         *     Returns:
         *         UserResponse model with current user's details
         */
        get: operations["get_current_user_info_users_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/filter-options": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Filter Options
         * @description Get distinct companies and sectors from users for filtering.
         *
         *     Args:
         *         user_service: User service instance (injected dependency)
         *         current_user: Current authenticated user (injected dependency)
         *     Returns:
         *         FilterOptionResponse model with lists of distinct companies and sectors
         *     return user_service.get_companies_sectors()
         */
        get: operations["get_filter_options_users_filter_options_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get User
         * @description Get user by ID.
         *
         *     Args:
         *         user_id: ID of the user to retrieve
         *         current_user: Current authenticated user (injected dependency)
         *         user_service: User service instance (injected dependency)
         *
         *     Returns:
         *         UserResponse model with user details
         *
         *     Raises:
         *         HTTPException: If user not found
         */
        get: operations["get_user_users__user_id__get"];
        /**
         * Update User
         * @description Update user by ID.
         *
         *     Args:
         *         user_id: ID of the user to update
         *         user_update: UserResponse model with updated data
         *         user_service: User service instance (injected dependency)
         *
         *     Returns:
         *         Updated UserResponse model
         *
         *     Raises:
         *         HTTPException: If user not found
         */
        put: operations["update_user_users__user_id__put"];
        post?: never;
        /**
         * Delete User
         * @description Delete user by ID.
         *
         *     Args:
         *         user_id: ID of the user to delete
         *         user_service: User service instance (injected dependency)
         *
         *     Raises:
         *         HTTPException: If user not found
         */
        delete: operations["delete_user_users__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Users
         * @description Get all connections/contacts of the authenticated user.
         *
         *     Args:
         *         offset: Pagination offset
         *         limit: Maximum number of results
         *         current_user: Current authenticated user (injected dependency)
         *         user_service: User service instance (injected dependency)
         *
         *     Returns:
         *         List of UserResponse models with the user's connections
         */
        get: operations["get_all_users_users__get"];
        put?: never;
        /**
         * Create User
         * @description Create a new connection/contact in your network.
         *
         *     Args:
         *         user_create: UserCreate model with new connection data
         *         current_user: Current authenticated user (injected dependency)
         *         user_service: User service instance (injected dependency)
         *
         *     Returns:
         *         Created UserResponse model
         *
         *     Raises:
         *         HTTPException: If user creation fails
         */
        post: operations["create_user_users__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/register_user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register User
         * @description Register a new user account.
         *
         *     Args:
         *         user_create: UserCreate model with new user data
         *         user_service: User service instance (injected dependency)
         *
         *     Returns:
         *         Created UserResponse model
         *
         *     Raises:
         *         HTTPException: If registration fails
         */
        post: operations["register_user_users_register_user_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user_id}/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change User Password
         * @description Change user's password.
         *
         *     Args:
         *         user_id: ID of the user whose password is to be changed
         *         new_password: New plain text password
         *         user_service: User service instance (injected dependency)
         *
         *     Returns:
         *         Success message if password change is successful
         *
         *     Raises:
         *         HTTPException: If user not found or password change fails
         */
        post: operations["change_user_password_users__user_id__change_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get All Connections
         * @description Get all connections in the system.
         *
         *     Args:
         *         current_user: Current authenticated user (injected dependency)
         *         connection_service: Connection service instance (injected dependency)
         *
         *     Returns:
         *         List of ConnectionResponse models
         */
        get: operations["get_all_connections_connections_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/{connection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Connection
         * @description Get connection by ID.
         *
         *     Args:
         *         connection_id: ID of the connection to retrieve
         *         current_user: Current authenticated user (injected dependency)
         *         connection_service: Connection service instance (injected dependency)
         *
         *     Returns:
         *         ConnectionResponse model with connection details
         *
         *     Raises:
         *         HTTPException: If connection not found
         */
        get: operations["get_connection_connections__connection_id__get"];
        /**
         * Update Connection
         * @description Update a connection by ID.
         *
         *     Args:
         *         connection_id: ID of the connection to update
         *         connection_update: ConnectionUpdate model with updated data
         *         current_user: Current authenticated user (injected dependency)
         *         connection_service: Connection service instance (injected dependency)
         *
         *     Returns:
         *         Updated ConnectionResponse model
         *
         *     Raises:
         *         HTTPException: If connection not found
         */
        put: operations["update_connection_connections__connection_id__put"];
        post?: never;
        /**
         * Delete Connection
         * @description Delete a connection by ID.
         *
         *     Args:
         *         connection_id: ID of the connection to delete
         *         current_user: Current authenticated user (injected dependency)
         *         connection_service: Connection service instance (injected dependency)
         *
         *     Raises:
         *         HTTPException: If deletion fails
         */
        delete: operations["delete_connection_connections__connection_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Connection
         * @description Create a new connection.
         *
         *     Args:
         *         connection_create: Connection data
         *         current_user: Current authenticated user (injected dependency)
         *         connection_service: Connection service instance (injected dependency)
         *
         *     Returns:
         *         ConnectionResponse model with created connection details
         */
        post: operations["create_connection_connections__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/user/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Connections For User
         * @description Get all connections for a specific user.
         *
         *     Args:
         *         user_id: ID of the user whose connections to retrieve
         *         current_user: Current authenticated user (injected dependency)
         *         connection_service: Connection service instance (injected dependency)
         *
         *     Returns:
         *         List of ConnectionResponse models
         */
        get: operations["get_connections_for_user_connections_user__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/connections/first-last-name/{connection_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get First Last Name By Connection Id
         * @description Get the first and last name of a connection by ID.
         *
         *     Args:
         *         connection_id: ID of the connection
         *         current_user: Current authenticated user (injected dependency)
         *         connection_service: Connection service instance (injected dependency)
         *     Returns:
         *         Full name string (first + last) of the connection
         */
        get: operations["get_first_last_name_by_connection_id_connections_first_last_name__connection_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referrals/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Current User Referrals
         * @description Get current authenticated user's referrals.
         *
         *     Args:
         *         current_user: Current authenticated user (injected dependency)
         *         referral_service: Referral service instance (injected dependency)
         *
         *     Returns:
         *         List of ReferralResponse models with current user's referrals
         */
        get: operations["get_current_user_referrals_referrals_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referrals/{referral_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Referral
         * @description Get referral by ID.
         *
         *     Args:
         *         referral_id: ID of the referral to retrieve
         *         current_user: Current authenticated user (injected dependency)
         *         referral_service: Referral service instance (injected dependency)
         *
         *     Returns:
         *         ReferralResponse model with referral details
         *
         *     Raises:
         *         HTTPException: If referral not found
         */
        get: operations["get_referral_referrals__referral_id__get"];
        /**
         * Update Referral
         * @description Update referral by ID.
         *
         *     Args:
         *         referral_id: ID of the referral to update
         *         referral_update: ReferralUpdate model with updated data
         *         current_user: Current authenticated user (injected dependency)
         *         referral_service: Referral service instance (injected dependency)
         *
         *     Returns:
         *         Updated ReferralResponse model
         *
         *     Raises:
         *         HTTPException: If referral not found
         */
        put: operations["update_referral_referrals__referral_id__put"];
        post?: never;
        /**
         * Delete Referral
         * @description Delete referral by ID.
         *
         *     Args:
         *         referral_id: ID of the referral to delete
         *         current_user: Current authenticated user (injected dependency)
         *         referral_service: Referral service instance (injected dependency)
         *
         *     Raises:
         *         HTTPException: If referral not found
         */
        delete: operations["delete_referral_referrals__referral_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/referrals/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Referral
         * @description Create a new referral.
         *
         *     Args:
         *         referral_create: Referral data
         *         current_user: Current authenticated user (injected dependency)
         *         referral_service: Referral service instance (injected dependency)
         *
         *     Returns:
         *         ReferralResponse model with created referral details
         */
        post: operations["create_referral_referrals__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Health check endpoint to verify database connectivity
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountCreate */
        AccountCreate: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Company */
            company?: string | null;
            /** Sector */
            sector?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Linkedin Url */
            linkedin_url?: string | null;
            /** How I Know Them */
            how_i_know_them?: string | null;
            /** When I Met Them */
            when_i_met_them?: string | null;
            /** Notes */
            notes?: string | null;
            /** Username */
            username: string;
            /** Password */
            password: string;
            /**
             * Is Me
             * @default true
             */
            is_me: boolean;
        };
        /** Body_generate_service_token_auth_service_token_post */
        Body_generate_service_token_auth_service_token_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** Body_login_auth_login_post */
        Body_login_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** ConnectionCreate */
        ConnectionCreate: {
            /** Person1 Id */
            person1_id: number;
            /** Person2 Id */
            person2_id: number;
            /** Relationship */
            relationship?: string | null;
            /** Strength */
            strength?: number | null;
            /** Context */
            context?: string | null;
            /** Last Interaction */
            last_interaction?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** ConnectionNameResponse */
        ConnectionNameResponse: {
            /** User1 Full Name */
            user1_full_name: string;
            /** User2 Full Name */
            user2_full_name: string;
        };
        /** ConnectionResponse */
        ConnectionResponse: {
            /** Id */
            id: number;
            /** Person1 Id */
            person1_id: number;
            /** Person2 Id */
            person2_id: number;
            /** Relationship */
            relationship?: string | null;
            /** Strength */
            strength?: number | null;
            /** Context */
            context?: string | null;
            /** Last Interaction */
            last_interaction?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** ConnectionUpdate */
        ConnectionUpdate: {
            /** Relationship */
            relationship?: string | null;
            /** Strength */
            strength?: number | null;
            /** Context */
            context?: string | null;
            /** Last Interaction */
            last_interaction?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** FilterOptionResponse */
        FilterOptionResponse: {
            /** Company */
            company: string[];
            /** Sector */
            sector: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ReferralCreate */
        ReferralCreate: {
            /** Referrer Id */
            referrer_id: number;
            /** Company */
            company?: string | null;
            /** Position */
            position?: string | null;
            /** Application Date */
            application_date?: string | null;
            /** Interview Date */
            interview_date?: string | null;
            /** Status */
            status?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** ReferralResponse */
        ReferralResponse: {
            /** Id */
            id: number;
            /** Referrer Id */
            referrer_id: number;
            /** Company */
            company?: string | null;
            /** Position */
            position?: string | null;
            /** Application Date */
            application_date?: string | null;
            /** Interview Date */
            interview_date?: string | null;
            /** Status */
            status?: string | null;
            /** Notes */
            notes?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** ReferralUpdate */
        ReferralUpdate: {
            /** Company */
            company?: string | null;
            /** Position */
            position?: string | null;
            /** Application Date */
            application_date?: string | null;
            /** Interview Date */
            interview_date?: string | null;
            /** Status */
            status?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /** UserCreate */
        UserCreate: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Company */
            company?: string | null;
            /** Sector */
            sector?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Linkedin Url */
            linkedin_url?: string | null;
            /** How I Know Them */
            how_i_know_them?: string | null;
            /** When I Met Them */
            when_i_met_them?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** UserResponse */
        UserResponse: {
            /** First Name */
            first_name: string;
            /** Last Name */
            last_name: string;
            /** Company */
            company?: string | null;
            /** Sector */
            sector?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Linkedin Url */
            linkedin_url?: string | null;
            /** How I Know Them */
            how_i_know_them?: string | null;
            /** When I Met Them */
            when_i_met_them?: string | null;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
            /** Is Me */
            is_me: boolean;
            /** Username */
            username?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** UserUpdate */
        UserUpdate: {
            /** First Name */
            first_name?: string | null;
            /** Last Name */
            last_name?: string | null;
            /** Company */
            company?: string | null;
            /** Sector */
            sector?: string | null;
            /** Username */
            username?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /** Linkedin Url */
            linkedin_url?: string | null;
            /** How I Know Them */
            how_i_know_them?: string | null;
            /** When I Met Them */
            when_i_met_them?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    generate_service_token_auth_service_token_post: {
        parameters: {
            query?: {
                expiration_days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_generate_service_token_auth_service_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    account_user_exist_auth_account_exists_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_current_user_info_users_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    get_filter_options_users_filter_options_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FilterOptionResponse"];
                };
            };
        };
    };
    get_user_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_users__user_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_users__user_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_users_users__get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_users__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_user_users_register_user_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AccountCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_user_password_users__user_id__change_password_post: {
        parameters: {
            query: {
                new_password: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_connections_connections_all_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionResponse"][];
                };
            };
        };
    };
    get_connection_connections__connection_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_connection_connections__connection_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_connection_connections__connection_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_connection_connections__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConnectionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_connections_for_user_connections_user__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_first_last_name_by_connection_id_connections_first_last_name__connection_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                connection_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionNameResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_referrals_referrals_me_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_referral_referrals__referral_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                referral_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_referral_referrals__referral_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                referral_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReferralUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_referral_referrals__referral_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                referral_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_referral_referrals__post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReferralCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferralResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
