const PersonData = [
  {
    id: 1,
    first_name: "John",
    last_name: "Doe",
    company: "Acme Inc.",
    sector: "Technology",
    email: "aasd@mail.com",
    phone: "123-456-7890",
    linkedin_url: "https://www.linkedin.com/in/johndoe",
    how_i_know_them: "Met at a conference",
    when_i_met_them: "2020-01-15",
    notes: "Interested in AI and machine learning.",
  },
  {
    id: 2,
    first_name: "Jane",
    last_name: "Smith",
    company: "Globex Corporation",
    sector: "Finance",
    email: "",
    phone: "987-654-3210",
    linkedin_url: "https://www.linkedin.com/in/janesmith",
    how_i_know_them: "Worked together on a project",
    when_i_met_them: "2019-06-10",
    notes: "Looking for opportunities in fintech.",
  },
  {
    id: 3,
    first_name: "Alice",
    last_name: "Johnson",
    company: "Initech",
    sector: "Software",
    email: "jester@mail.com",
    phone: "555-123-4567",
    linkedin_url: "https://www.linkedin.com/in/alicejohnson",
    how_i_know_them: "Friend of a friend",
    when_i_met_them: "2021-03-22",
    notes: "Interested in software development and startups.",
  },
  {
    id: 4,
    first_name: "Bob",
    last_name: "Brown",
    company: "Umbrella Corp",
    sector: "Pharmaceuticals",
    email: "",
    phone: "444-555-6666",
    linkedin_url: "https://www.linkedin.com/in/bobbrown",
    how_i_know_them: "Met at a networking event",
    when_i_met_them: "2018-11-05",
    notes: "Looking for collaborations in biotech.",
  },
];

export default PersonData;
